# Generated by Django 5.2.6 on 2025-09-14 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreBuilder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resumes',
            old_name='eduaction',
            new_name='education',
        ),
    ]
