# Generated by Django 5.2.6 on 2025-09-20 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreBuilder', '0002_rename_eduaction_resumes_education'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumes',
            name='education',
        ),
        migrations.RemoveField(
            model_name='resumes',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='resumes',
            name='name',
        ),
        migrations.RemoveField(
            model_name='resumes',
            name='skills',
        ),
        migrations.AddField(
            model_name='resumes',
            name='achievements',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='resumes',
            name='certificate1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resumes',
            name='certificate1Link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='resumes',
            name='certificate2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resumes',
            name='certificate2Link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='resumes',
            name='collegeBranch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resumes',
            name='collegeEnd',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resumes',
            name='collegeLocation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resumes',
            name='collegeName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resumes',
            name='collegeStart',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resumes',
            name='companyEnd',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resumes',
            name='companyLocation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resumes',
            name='companyName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resumes',
            name='companyPosition',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resumes',
            name='companyStart',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resumes',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resumes',
            name='firstName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resumes',
            name='lastName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resumes',
            name='linkedinLink',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='resumes',
            name='mobileNumber',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='resumes',
            name='portfolioLink',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='resumes',
            name='projectHowYouSolved',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='resumes',
            name='projectName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resumes',
            name='projectTime',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resumes',
            name='projectToolsUsed',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='resumes',
            name='skillsTechnical',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='resumes',
            name='skillsTools',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='resumes',
            name='summary',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
