# Generated by Django 5.2.6 on 2025-09-23 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreBuilder', '0003_remove_resumes_education_remove_resumes_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumes',
            name='collegeAchivements',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
