# Generated by Django 5.2.6 on 2025-09-23 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreBuilder', '0004_resumes_collegeachivements'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumes',
            name='companyWorkDescription',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
